# Generated by Django 3.2.22 on 2024-01-29 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('agreement_accepted', models.BooleanField(default=False)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('full_payment_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_status', models.IntegerField(choices=[(0, 'Obekräftad'), (1, 'Bekräftad'), (2, 'Reserv')], default=0)),
                ('competition_level', models.CharField(choices=[('Lätt C', 'Lätt C'), ('Lätt B', 'Lätt B'), ('Lätt A', 'Lätt A'), ('MSV C', 'MSV C'), ('MSV B', 'MSV B'), ('MSV A', 'MSV A'), ('Grand Prix', 'Grand Prix')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdultEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('total_spots', models.PositiveIntegerField(default=6)),
                ('booked_spots', models.PositiveIntegerField(default=0)),
                ('reserved_spots', models.PositiveIntegerField(default=0)),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='KidsEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('total_spots', models.PositiveIntegerField(default=6)),
                ('booked_spots', models.PositiveIntegerField(default=0)),
                ('reserved_spots', models.PositiveIntegerField(default=0)),
            ],
            bases=('events.event',),
        ),
    ]
