# Generated by Django 3.2.22 on 2024-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultevent',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kidsevent',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
