# Generated by Django 3.2.22 on 2024-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20240129_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultevent',
            name='reserved_spots',
        ),
        migrations.RemoveField(
            model_name='adultevent',
            name='total_spots',
        ),
        migrations.RemoveField(
            model_name='kidsevent',
            name='reserved_spots',
        ),
        migrations.RemoveField(
            model_name='kidsevent',
            name='total_spots',
        ),
        migrations.AddField(
            model_name='adultevent',
            name='horse_box_spots',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='AdultEvent', max_length=20),
        ),
        migrations.AddField(
            model_name='kidsevent',
            name='horse_box_spots',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'Obekräftad'), (1, 'Bekräftad')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
