# Generated by Django 3.2.22 on 2024-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20240202_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultevent',
            name='wants_box_spot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
