# Generated by Django 3.2.22 on 2024-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_adultevent_wants_box_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsevent',
            name='wants_box_spot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
